// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrofHMYkUMtZwuAqIbBZTlwcjMHoAuGqc',
    appId: '1:503466312371:web:d03673dbbc1c4a151b26c6',
    messagingSenderId: '503466312371',
    projectId: 'triptravelprojects',
    authDomain: 'triptravelprojects.firebaseapp.com',
    storageBucket: 'triptravelprojects.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODxa12ucNy5kUqyeaaCu3aKuxZmMoX7g',
    appId: '1:503466312371:android:a31845ca3fe8eed71b26c6',
    messagingSenderId: '503466312371',
    projectId: 'triptravelprojects',
    storageBucket: 'triptravelprojects.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNOsF8Hs79uKW4fc7a9BqPuM4trYLF0LQ',
    appId: '1:503466312371:ios:e7766469133f79611b26c6',
    messagingSenderId: '503466312371',
    projectId: 'triptravelprojects',
    storageBucket: 'triptravelprojects.firebasestorage.app',
    iosBundleId: 'com.example.triptravelprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNOsF8Hs79uKW4fc7a9BqPuM4trYLF0LQ',
    appId: '1:503466312371:ios:e7766469133f79611b26c6',
    messagingSenderId: '503466312371',
    projectId: 'triptravelprojects',
    storageBucket: 'triptravelprojects.firebasestorage.app',
    iosBundleId: 'com.example.triptravelprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrofHMYkUMtZwuAqIbBZTlwcjMHoAuGqc',
    appId: '1:503466312371:web:6e5fd61845e918dd1b26c6',
    messagingSenderId: '503466312371',
    projectId: 'triptravelprojects',
    authDomain: 'triptravelprojects.firebaseapp.com',
    storageBucket: 'triptravelprojects.firebasestorage.app',
  );
}
